name: Docker Meta
description: GitHub Action to extract metadata (tags, labels) for Docker
author: mikian
branding:
  color: blue
  icon: layers

inputs:
  repository:
    description: Docker repository where image is to be published
    required: true

outputs:
  repositoryTag:
    description: Generated full image:tag format of published image
  repository:
    description: Full URL of Published Image
  tag:
    description: Generated Main Docker Tag for Commit
  tags:
    description: Generated Docker tags
  labels:
    description: Generated Docker labels
  sha:
    description: Commit SHA for docker build

runs:
  using: node12
  main: index.js
